fix: eslint error for lineBreak style

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,15 +1,16 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-npm run lint ||
-{
-  echo "Lint failed"
-  exit 1
-}
 
 npm run lint:fix ||
 {
   echo "Lint fix failed"
+  exit 1
+}
+
+npm run lint ||
+{
+  echo "Lint failed"
   exit 1
 }
 
